-- Insertando datos en la tabla 'producto'
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (1, 'https://www.gourmet.com.co/wp-content/uploads/2020/02/GalletasAvena-Gourmet-1.jpg', 'Disponible', 'Galletas', 'Galletas de avena y miel', 3000, 'Panaderia');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (2, 'https://previews.123rf.com/images/ocusfocus/ocusfocus1505/ocusfocus150500032/40402110-cuadro-delicioso-y-tentador-llena-de-donas-con-diferentes-sabores-y-coberturas-en-la-alimentaci%C3%B3n.jpg', 'Disponible', 'Donas', 'Donas glaseadas', 2500, 'Pasteleria');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (3, 'https://www.southernliving.com/thmb/UW4kKKL-_M3WgP7pkL6Pb6lwcgM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Ham_Sandwich_011-1-49227336bc074513aaf8fdbde440eafe.jpg', 'Disponible', 'Sandwich', 'Sandwich de jamón y queso', 8000, 'Comida rápida');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (4, 'https://www.recetasnestle.com.co/sites/default/files/srh_recipes/07b7133ace77e9539864e423774ef443.jpeg', 'Disponible', 'Ensalada', 'Ensalada de frutas', 7000, 'Saludable');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (5, 'https://boutic.cl/cdn/shop/products/NaranjaNatural_portada_1512x.png?v=1667598605', 'Disponible', 'Jugo', 'Jugo de naranja natural', 5000, 'Bebidas');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (6, 'https://i.pinimg.com/474x/04/e3/6f/04e36f80e52bd9bfba42bb83d77fb461.jpg', 'Disponible', 'Café', 'Café americano', 3000, 'Bebidas');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (8, 'https://img.interempresas.net/fotos/2520538.jpeg', 'Disponible', 'Agua', 'Agua mineral', 2000, 'Bebidas');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (9, 'https://res.cloudinary.com/riqra/image/upload/w_656,h_656,c_limit,q_auto,f_auto/v1678811256/sellers/2/igykzmu1fvpxol9fdon0.jpg', 'Disponible', 'Refresco', 'Refresco de cola', 2500, 'Bebidas');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (11, 'https://img.delicious.com.au/RzgR3kXD/w1200/del/2015/12/cornetti-italian-croissants-24713-1.jpg', 'Disponible', 'Croissant', 'Croissant de mantequilla', 3500, 'Panaderia');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (12, 'https://www.lactaidenespanol.com/sites/lactaid_us/files/recipe-images/giantblueberrymuffins.png', 'Disponible', 'Muffin', 'Muffin de arándanos', 4000, 'Pasteleria');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (13, 'https://imag.bonviveur.com/bagels-en-el-plato.jpg', 'Disponible', 'Bagel', 'Bagel con queso crema', 3000, 'Panaderia');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (14, 'https://www.aki.com.ec/wp-content/uploads/2021/01/foto-receta-pastel-chocolate.jpg', 'Disponible', 'Torta', 'Torta de chocolate', 15000, 'Pasteleria');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (15, 'https://www.midiariodecocina.com/wp-content/uploads/2016/06/Pan-integral-01.jpg', 'Disponible', 'Pan Integral', 'Pan integral con semillas', 5000, 'Panaderia');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (17, 'https://www.thecountrycook.net/wp-content/uploads/2022/04/thumbnail-Homemade-Churros.jpg', 'Disponible', 'Churros', 'Churros con azúcar y canela', 2000, 'Panaderia');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (18, 'https://editorialtelevisa.brightspotcdn.com/wp-content/uploads/2020/11/quiche-que-es-con-queso-y-espinacas.jpg', 'Disponible', 'Quiche', 'Quiche de espinacas y queso', 12000, 'Panaderia');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (19, 'https://content-cocina.lecturas.com/medio/2022/12/08/eclairs-de-crema-y-chocolate_46bd7e43_1200x1200.jpg', 'Disponible', 'Eclair', 'Eclair de chocolate', 3000, 'Pasteleria');
INSERT INTO producto (id, urlimagen, confirmaciondedisponibilidad, nombre, descripcion, precio, categoria) VALUES (20, 'https://www.richs.co.za/wp-content/uploads/2021/03/Medium-09751_ZA_Product-Beauty.jpg', 'Disponible', 'Baguette', 'Baguette francesa', 3500, 'Panaderia');
